import { processLessons } from "../../../shared/learningHub";
import type { ProductLanguage } from "./productLanguage";

type Lesson = typeof processLessons[number];
type LessonCopy = { title: string; concept: string; equipment: string; observe: string; misconception: string; question: string; options: readonly [string, string] };

const copy: Record<"en" | "ja", Record<Lesson["id"], LessonCopy>> = {
  en: {
    wafer: { title: "Wafer preparation", concept: "Prepare the substrate for circuits by slicing silicon single crystals into thin wafers and finishing their surfaces.", equipment: "Crystal growth, cutting, and polishing equipment", observe: "When comparing surfaces, were the inspection conditions and positions the same?", misconception: "Preparing a wafer does not mean the circuit is already complete.", question: "What is the wafer's role?", options: ["A box for packaging finished chips", "A substrate on which circuits are formed"] },
    oxidation: { title: "Oxidation", concept: "Form an oxide layer on a silicon surface. The layer can serve insulation or protection roles in device structures.", equipment: "Thermal oxidation equipment", observe: "Are the film-thickness and uniformity results being compared under the same process conditions?", misconception: "Oxidation is not the same as every type of thin-film deposition.", question: "What is a common role of an oxide layer?", options: ["Insulation and protection", "External packaging of a finished chip"] },
    photo: { title: "Photolithography", concept: "Transfer a circuit pattern to a light-sensitive resist. Coating, exposure, and development play different roles.", equipment: "Coating, developing, and lithography equipment", observe: "Did you compare pattern position and shape against the same reference?", misconception: "Forming a resist pattern and etching the material beneath it are separate processes.", question: "What is the central task of photolithography?", options: ["Forming a pattern in resist", "Connecting a chip to external terminals"] },
    etch: { title: "Etch", concept: "Selectively remove material to leave the required pattern. Some dry-etch processes use plasma.", equipment: "Plasma etch equipment", observe: "Did you compare pressure, flow, RF, and temperature with normal records from the same process phase?", misconception: "A pressure change alone cannot confirm a failed part or its cause.", question: "If chamber pressure changes, what should you consider first?", options: ["Declare a specific part failed", "Compare same-phase normal records and other signals"] },
    deposition: { title: "Deposition and ion implantation", concept: "Deposition forms a thin film on a surface. Ion implantation is a separate process that introduces dopant ions to adjust electrical properties.", equipment: "Thin-film deposition and ion implantation equipment", observe: "Is the observation about film properties or electrical properties?", misconception: "These appear together in an introductory grouping but use different principles.", question: "How are deposition and ion implantation related?", options: ["The same task with different names", "Different tasks with different purposes and methods"] },
    metal: { title: "Interconnect", concept: "Create conductive paths between devices. Multilayer structures require both connections and insulation.", equipment: "Metal-film and interconnect equipment", observe: "Did you distinguish electrical connectivity measurements from equipment sensor records?", misconception: "Seeing a metal film does not prove that every connection works.", question: "What is the purpose of interconnect?", options: ["Electrical connections between devices", "Cutting a wafer disk"] },
    eds: { title: "Electrical die sorting", concept: "Test and classify the electrical characteristics of individual chips while still on the wafer, before packaging.", equipment: "Probers and electrical test equipment", observe: "Did you interpret wafer-map test results and equipment condition as separate evidence?", misconception: "Chip test results alone do not prove the cause of an equipment failure.", question: "What does EDS directly test?", options: ["The cause of every manufacturing-equipment failure", "Electrical characteristics of chips on a wafer"] },
    packaging: { title: "Packaging", concept: "Protect the chip and connect it to external circuits. Connection and protection structures vary by package type.", equipment: "Die attach, bonding, and encapsulation equipment", observe: "Did you separate connection condition from visual condition?", misconception: "Packaging is more than simply putting a chip in a box.", question: "What does packaging provide?", options: ["Chip protection and external connection", "Every front-end patterning step"] },
  },
  ja: {
    wafer: { title: "ウェーハ製造", concept: "回路を作る土台を準備します。シリコン単結晶から薄い円板を得て表面を整えます。", equipment: "結晶成長・切断・研磨装置", observe: "表面状態を比較するとき、検査条件と位置は同じですか？", misconception: "ウェーハの準備が終わっても回路が完成したわけではありません。", question: "ウェーハの役割は？", options: ["完成したチップを包む箱", "回路を形成する基板"] },
    oxidation: { title: "酸化", concept: "シリコン表面に酸化膜を形成します。酸化膜は素子構造で絶縁や保護などの役割を担います。", equipment: "酸化用熱処理装置", observe: "比較する膜厚と均一性は同じ工程条件の結果ですか？", misconception: "酸化とすべての薄膜堆積は同じ工程ではありません。", question: "酸化膜の代表的な役割は？", options: ["絶縁と保護", "完成チップの外部包装"] },
    photo: { title: "フォトリソグラフィ", concept: "光に反応するレジストに回路パターンを転写します。塗布・露光・現像には異なる役割があります。", equipment: "塗布・現像装置と露光装置", observe: "パターンの位置と形状を同じ基準で比較しましたか？", misconception: "レジストにパターンを作ることと下層をエッチングすることは別です。", question: "フォト工程の中心は？", options: ["レジストにパターンを形成する", "チップを外部端子につなぐ"] },
    etch: { title: "エッチング", concept: "必要なパターンを残すため材料を選択的に除去します。ドライエッチングにはプラズマを用いる方式があります。", equipment: "プラズマエッチング装置", observe: "同じ工程段階の正常記録と圧力・流量・RF・温度を比較しましたか？", misconception: "圧力変化だけで故障部品や原因は確定できません。", question: "チャンバー圧力が変わったとき最初に考えることは？", options: ["特定部品の故障と断定する", "段階別の正常記録と他の信号を比較する"] },
    deposition: { title: "堆積・イオン注入", concept: "堆積は表面に薄膜を作る工程です。イオン注入は不純物イオンを導入して電気的特性を調整する別の工程です。", equipment: "薄膜堆積装置・イオン注入装置", observe: "観察対象が膜の特性か電気的特性かをまず区別しましたか？", misconception: "入門分類では一緒に扱いますが、両者は同じ原理ではありません。", question: "堆積とイオン注入の関係は？", options: ["名前だけが異なる同一作業", "目的と方法が異なる作業"] },
    metal: { title: "金属配線", concept: "素子間に電気信号を通す経路を作ります。多層構造では接続と絶縁の両方を考慮します。", equipment: "金属膜形成・配線関連装置", observe: "接続状態の測定結果と装置センサー記録を混同していませんか？", misconception: "金属膜が見えるだけではすべての接続が正常とは判断できません。", question: "金属配線の目的は？", options: ["素子間の電気的接続", "ウェーハ円板の切断"] },
    eds: { title: "EDS（電気的選別）", concept: "ウェーハ上で個々のチップの電気的特性を検査・分類します。結果はパッケージング前のチップ状態を判断する資料です。", equipment: "プローバー・電気検査装置", observe: "ウェーハマップの検査結果と装置状態を別の根拠として解釈しましたか？", misconception: "チップの検査結果だけでは製造装置の故障原因は証明できません。", question: "EDSが直接検査する対象は？", options: ["すべての製造装置の故障原因", "ウェーハ上のチップの電気的特性"] },
    packaging: { title: "パッケージング", concept: "チップを保護し、外部回路と接続できるようにします。接続と保護構造はパッケージ方式によって異なります。", equipment: "ダイ接合・ボンディング・封止関連装置", observe: "接続状態と外観状態を別々の確認項目に分けましたか？", misconception: "パッケージングは単に箱に入れる作業だけではありません。", question: "パッケージングの役割は？", options: ["チップの保護と外部接続", "すべての前工程パターン形成"] },
  },
};

export function localizeLesson(language: ProductLanguage, lesson: Lesson): Lesson | (Omit<Lesson, "title" | "concept" | "equipment" | "observe" | "misconception" | "question" | "options"> & LessonCopy) {
  return language === "ko" ? lesson : { ...lesson, ...copy[language][lesson.id] };
}
