export const processLessons = [
  { id: "wafer", title: "웨이퍼 제조", english: "Wafer", concept: "회로를 만들 바탕을 준비합니다. 실리콘 단결정에서 얇은 원판을 얻고 표면을 다듬습니다.", equipment: "결정 성장·절단·연마 장비", observe: "표면 상태를 비교할 때 같은 검사 조건과 위치를 확인했나요?", misconception: "웨이퍼 준비가 끝났다고 회로까지 완성된 것은 아닙니다.", question: "웨이퍼의 역할은?", options: ["완성된 칩을 포장하는 상자", "회로를 형성할 기판"], answer: 1 },
  { id: "oxidation", title: "산화", english: "Oxidation", concept: "실리콘 표면에 산화막을 형성합니다. 산화막은 소자 구조에서 절연이나 보호 등의 역할을 합니다.", equipment: "산화용 열처리 장비", observe: "비교하는 막 두께와 균일도는 같은 공정 조건의 결과인가요?", misconception: "산화와 모든 종류의 박막 증착은 같은 공정이 아닙니다.", question: "산화막의 대표적인 역할은?", options: ["절연과 보호", "완성 칩의 외부 포장"], answer: 0 },
  { id: "photo", title: "포토", english: "Photolithography", concept: "빛에 반응하는 감광막에 회로 패턴을 옮깁니다. 감광막 도포·노광·현상은 패턴 형성을 위한 서로 다른 역할을 합니다.", equipment: "도포·현상 장비와 노광 장비", observe: "패턴의 위치와 모양을 같은 기준으로 비교했나요?", misconception: "포토에서 패턴을 만드는 것과 아래 재료를 식각하는 것은 구분해야 합니다.", question: "포토 공정의 핵심은?", options: ["감광막에 패턴을 형성하기", "칩을 외부 단자에 연결하기"], answer: 0 },
  { id: "etch", title: "식각", english: "Etch", concept: "필요한 패턴을 남기도록 재료를 선택적으로 제거합니다. 건식 식각 중에는 플라즈마를 활용하는 방식이 있습니다.", equipment: "플라즈마 식각 장비", observe: "같은 공정 단계의 정상 기록과 압력·유량·RF·온도를 함께 비교했나요?", misconception: "압력 변화 하나만으로 고장 부품이나 원인을 확정할 수 없습니다.", question: "챔버 압력이 달라졌을 때 먼저 할 판단은?", options: ["특정 부품 고장으로 확정하기", "단계별 정상 기록과 다른 신호도 비교하기"], answer: 1 },
  { id: "deposition", title: "증착·이온 주입", english: "Deposition / Implantation", concept: "증착은 표면에 얇은 막을 만드는 과정입니다. 이온 주입은 불순물 이온을 도입해 전기적 특성을 조절하는 별개의 과정입니다.", equipment: "박막 증착 장비·이온 주입 장비", observe: "관찰 대상이 막의 특성인지 전기적 특성인지 먼저 구분했나요?", misconception: "입문 분류에서 함께 소개하지만 두 작업은 같은 원리가 아닙니다.", question: "증착과 이온 주입의 관계는?", options: ["이름만 다른 동일한 작업", "목적과 방식이 다른 작업"], answer: 1 },
  { id: "metal", title: "금속 배선", english: "Interconnect", concept: "소자 사이에 전기 신호가 흐를 연결 경로를 만듭니다. 여러 층의 구조에서 필요한 연결과 절연을 함께 고려합니다.", equipment: "금속막 형성·배선 관련 장비", observe: "연결 상태에 관한 측정 결과와 장비 센서 기록을 혼동하지 않았나요?", misconception: "금속막이 보인다는 사실만으로 모든 연결이 정상이라고 판단할 수 없습니다.", question: "금속 배선의 목적은?", options: ["소자 사이의 전기적 연결", "웨이퍼 원판 절단"], answer: 0 },
  { id: "eds", title: "EDS", english: "Electrical Die Sorting", concept: "웨이퍼 상태에서 개별 칩의 전기적 특성을 검사하고 분류합니다. 검사 결과는 패키징 전 칩 상태를 판단하는 자료입니다.", equipment: "프로버·전기 검사 장비", observe: "웨이퍼 맵의 검사 결과와 장비 상태는 별도의 근거로 해석했나요?", misconception: "칩 검사 결과만으로 제조 장비의 고장 원인이 입증되지는 않습니다.", question: "EDS가 직접 검사하는 대상은?", options: ["모든 제조 장비의 고장 원인", "웨이퍼 위 칩의 전기적 특성"], answer: 1 },
  { id: "packaging", title: "패키징", english: "Packaging", concept: "칩을 보호하고 외부 회로와 연결할 수 있도록 구성합니다. 칩 연결과 보호 구조는 패키지 방식에 따라 달라집니다.", equipment: "다이 접합·본딩·봉지 관련 장비", observe: "연결 상태와 외관 상태를 서로 다른 확인 항목으로 나눴나요?", misconception: "패키징은 단순히 상자에 넣는 작업만을 뜻하지 않습니다.", question: "패키징이 담당하는 역할은?", options: ["칩 보호와 외부 연결", "모든 전공정 패턴 형성"], answer: 0 },
] as const;

export const processOverviewSource = "https://semiconductor.samsung.com/kr/support/tools-resources/fabrication-process/";
export const etchEquipmentSource = "https://www.lamresearch.com/product/kiyo-product-family/";
